'use client'

import '@/app/globals.css'
import {Outfit} from 'next/font/google'

const outfit = Outfit({subsets: ['latin']})

export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode
  }) {
  const metadata = {
    title: 'Irfan Fakhri - Software Engineer',
    description: 'Generated by create next app',
    author: 'Irfan Fakhri',
    keywords: 'web design, web, web apps, html, css, js, ts, node.js, next, vue, react, go, golang, php, laravel, mongodb, sql, mysql, postgre'
  }

  return (
    <html lang="en">
    <head>
      <title>{metadata.title}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content={metadata.description}/>
      <meta name="keywords" content={metadata.keywords}/>
      <meta name="author" content={metadata.author}/>
    </head>
    <body className={outfit.className}>
    <main className="relative">
      {children}
    </main>
    </body>
    </html>
  )
}
