'use client'

import '@/app/globals.css'
import {Outfit} from 'next/font/google'

const outfit = Outfit({subsets: ['latin']})


export default function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode
  }) {
  const metadata = {
    title: 'Irfan Fakhri - Software Engineer',
    description: 'Generated by create next app',
  }

  return (
    <html lang="en">
    <head>
      <title>{metadata.title}</title>
    </head>
    <body className={outfit.className}>
    <main className="relative">
      {children}
    </main>
    </body>
    </html>
  )
}
